#!/bin/bash

# Color definitions
readonly RED='\033[1;31m'
readonly GREEN='\033[1;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[1;34m'
readonly PURPLE='\033[1;35m'
readonly CYAN='\033[1;36m'
readonly GRAY='\033[1;90m'
readonly NC='\033[0m' # No Color



main() {
    
    local mode=$1
    level_name=$2
    if [[ $# -eq 0 ]]; then
     
        exit 0
    elif [[ "$#" -ne 2 && "$mode" != 'sandbox' ]]; then
    
        exit 1
    elif [[ "$mode" != 'play' && "$mode" != 'sandbox' ]]; then
   
        exit 1
    fi
}

main "$@"
